server:
  port: 8080
spring:
  application:
    name: ToDos
  profiles:
    active: default-security
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: ${SSO_AUTH_SERVER:http://localhost:8585/auth}
  realm: ${SSO_REALM:realm}
  resource: ${SSO_RESOURCE:todos}
  bearer-only: true
  principal-attribute: preferred_username
  
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always